blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url:  https://github.com/FreeTubeApp/FreeTube/discussions/categories/q-a
    about: Please ask and answer questions here.
  - name: Join our Matrix Community
    url: https://matrix.to/#/+freetube:matrix.org
