blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url:  https://github.com/FreeTubeApp/FreeTube/discussions/categories/q-a
  - name: Join our Matrix Community
    url: https://matrix.to/#/+freetube:matrix.org
  - name: Start a discussion
    url:  https://github.com/FreeTubeApp/FreeTube/discussions/categories/general
